NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
HORIZON_URL = "https://horizon.stellar.org"

ORG_NAME = "Lumenaire"
ORG_LOGO = "https://raw.githubusercontent.com/XLMNR/LUMENAIRE/main/logo.png"
ORG_URL = "https://thelumenaire.com"
ORG_DESCRIPTION = "Lumenaire is the signal in the noise..."
ORG_TWITTER = "https://x.com/X_LMNR"
ORG_TELEGRAM = "https://t.me/X_LMNR"
ORG_GITHUB = "https://github.com/XLMNR"
ORG_SUPPORT_EMAIL = "LMNR013@GMAIL.COM"

FEDERATION_SERVER = "https://federation.thelumenaire.com/federation"
AUTH_SERVER = "https://auth.thelumenaire.com/auth"

[[CURRENCIES]]
code = "LMNR"
issuer = "GDKA6WVMFSA73BMEVKPO6WXSSWP4MPRBDJVSXLLSEVIEVH226L5RJ7NL"
status = "live"
display_decimals = 7
name = "LUMENAIRE"
desc = "Lumenaire is the signal in the noise..."
image = "https://raw.githubusercontent.com/XLMNR/LUMENAIRE/main/lmnr-logo.png"
fixed_number = 0
max_number = 0
is_unlimited = true
is_asset_anchored = false
anchor_asset_type = "crypto"
conditions = "No ICO, no pre-sale, 100% fair launches, ZERO token allocation"
home_domain = "thelumenaire.com"
