VERSION="2.3.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDKA6WVMFSA73BMEVKPO6WXSSWP4MPRBDJVSXLLSEVIEVH226L5RJ7NL"
]

[DOCUMENTATION]
ORG_NAME="Lumenaire "
ORG_URL="https://www.thelumenaire.com"
ORG_LOGO="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-FM9jrpQ1q7uNnzhoHwOzZEmeYNeuKA.png"
ORG_DESCRIPTION="Stellar is the infrastructure. Lumenaire is the culture."
ORG_TWITTER="https://twitter.com/X_LMNR"
ORG_OFFICIAL_EMAIL="LMNR013@gmail.com"

[[CURRENCIES]]
code="xLMNR"
issuer="GDKA6WVMFSA73BMEVKPO6WXSSWP4MPRBDJVSXLLSEVIEVH226L5RJ7NL"
is_asset_anchored=false
display_decimals=7
name="Lumenaire v2"
desc="Built on Stellar. Powered by conviction! Lumenaire isn’t just a token..  it’s the culture layer of the chain. ⚡ While others build infrastructure… we build movement. XLM moves value. LMNR moves people.."
conditions="LMNR is a community token with no intrinsic value or expectation of profit."
image="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-FM9jrpQ1q7uNnzhoHwOzZEmeYNeuKA.png"
status="live"

[[PRINCIPALS]]
email="LMNR013@gmail.com"
twitter="https://twitter.com/X_LMNR"
telegram="https://t.me/X_LMNR"
